export type HiraganaItem = {
  kana: string;
  romaji: string;
  traps: string[];
};

export const HIRAGANA_DATA: HiraganaItem[] = [
  { kana: "あ", romaji: "a", traps: ["o", "u", "ya"] },
  { kana: "い", romaji: "i", traps:   ["ri", "e", "chi"] },
  { kana: "う", romaji: "u", traps: ["a", "o", "tsu"] },
  { kana: "え", romaji: "e", traps: ["i", "ke", "sa"] },
  { kana: "お", romaji: "o", traps: ["a", "u", "ho"] },

  { kana: "か", romaji: "ka", traps: ["ga", "ko", "ki"] },
  { kana: "き", romaji: "ki", traps: ["sa", "ka", "gi"] },
  { kana: "く", romaji: "ku", traps: ["ke", "ta", "gu"] },
  { kana: "け", romaji: "ke", traps: ["ku", "se", "ge"] },
  { kana: "こ", romaji: "ko", traps: ["ka", "to", "go"] },

  { kana: "さ", romaji: "sa", traps: ["chi", "ki", "shi"] },
  { kana: "し", romaji: "shi", traps: ["tsu", "ji", "chi"] },
  { kana: "す", romaji: "su", traps: ["nu", "mu", "zu"] },
  { kana: "せ", romaji: "se", traps: ["ke", "ze", "e"] },
  { kana: "そ", romaji: "so", traps: ["n", "zo", "shi"] },

  { kana: "た", romaji: "ta", traps: ["da", "ku", "chi"] },
  { kana: "ち", romaji: "chi", traps: ["sa", "shi", "tsu"] },
  { kana: "つ", romaji: "tsu", traps: ["shi", "chi", "su"] },
  { kana: "て", romaji: "te", traps: ["de", "to", "ke"] },
  { kana: "と", romaji: "to", traps: ["ko", "do", "te"] },

  { kana: "な", romaji: "na", traps: ["ta", "ha", "ma"] },
  { kana: "に", romaji: "ni", traps: ["ri", "mi", "i"] },
  { kana: "ぬ", romaji: "nu", traps: ["su", "ne", "mu"] },
  { kana: "ね", romaji: "ne", traps: ["re", "nu", "me"] },
  { kana: "の", romaji: "no", traps: ["ho", "o", "to"] },

  { kana: "は", romaji: "ha", traps: ["ba", "pa", "na"] },
  { kana: "ひ", romaji: "hi", traps: ["bi", "pi", "chi"] },
  { kana: "ふ", romaji: "fu", traps: ["hu", "bu", "pu"] },
  { kana: "へ", romaji: "he", traps: ["be", "pe", "ho"] },
  { kana: "ほ", romaji: "ho", traps: ["bo", "po", "no"] },

  { kana: "ま", romaji: "ma", traps: ["na", "mu", "me"] },
  { kana: "み", romaji: "mi", traps: ["ni", "ri", "bi"] },
  { kana: "む", romaji: "mu", traps: ["su", "nu", "ma"] },
  { kana: "め", romaji: "me", traps: ["ne", "re", "ma"] },
  { kana: "も", romaji: "mo", traps: ["ho", "yo", "to"] },

  { kana: "や", romaji: "ya", traps: ["yu", "a", "ra"] },
  { kana: "ゆ", romaji: "yu", traps: ["ya", "yo", "u"] },
  { kana: "よ", romaji: "yo", traps: ["yu", "mo", "ro"] },

  { kana: "ら", romaji: "ra", traps: ["ya", "na", "wa"] },
  { kana: "り", romaji: "ri", traps: ["i", "ni", "mi"] },
  { kana: "る", romaji: "ru", traps: ["re", "ro", "u"] },
  { kana: "れ", romaji: "re", traps: ["ne", "ru", "me"] },
  { kana: "ろ", romaji: "ro", traps: ["yo", "ru", "to"] },

  { kana: "わ", romaji: "wa", traps: ["ra", "ma", "a"] },
  { kana: "を", romaji: "wo", traps: ["o", "wa", "ro"] },
  { kana: "ん", romaji: "n", traps: ["so", "shi", "no"] },

  { kana: "が", romaji: "ga", traps: ["ka", "gi", "go"] },
  { kana: "ぎ", romaji: "gi", traps: ["ki", "ji", "bi"] },
  { kana: "ぐ", romaji: "gu", traps: ["ku", "zu", "go"] },
  { kana: "げ", romaji: "ge", traps: ["ke", "ze", "go"] },
  { kana: "ご", romaji: "go", traps: ["ko", "gu", "ga"] },

  { kana: "ざ", romaji: "za", traps: ["sa", "ji", "zo"] },
  { kana: "じ", romaji: "ji", traps: ["shi", "gi", "chi"] },
  { kana: "ず", romaji: "zu", traps: ["su", "gu", "tsu"] },
  { kana: "ぜ", romaji: "ze", traps: ["se", "ge", "de"] },
  { kana: "ぞ", romaji: "zo", traps: ["so", "go", "do"] },

  { kana: "だ", romaji: "da", traps: ["ta", "de", "ba"] },
  { kana: "ぢ", romaji: "ji", traps: ["chi", "ji", "di"] },
  { kana: "づ", romaji: "zu", traps: ["tsu", "zu", "du"] },
  { kana: "で", romaji: "de", traps: ["te", "ze", "ge"] },
  { kana: "ど", romaji: "do", traps: ["to", "zo", "bo"] },

  { kana: "ば", romaji: "ba", traps: ["ha", "pa", "da"] },
  { kana: "び", romaji: "bi", traps: ["hi", "pi", "gi"] },
  { kana: "ぶ", romaji: "bu", traps: ["fu", "pu", "gu"] },
  { kana: "べ", romaji: "be", traps: ["he", "pe", "de"] },
  { kana: "ぼ", romaji: "bo", traps: ["ho", "po", "do"] },

  { kana: "ぱ", romaji: "pa", traps: ["ha", "ba", "ta"] },
  { kana: "ぴ", romaji: "pi", traps: ["hi", "bi", "chi"] },
  { kana: "ぷ", romaji: "pu", traps: ["fu", "bu", "tsu"] },
  { kana: "ぺ", romaji: "pe", traps: ["he", "be", "re"] },
  { kana: "ぽ", romaji: "po", traps: ["ho", "bo", "to"] },

  { kana: "きゃ", romaji: "kya", traps: ["kyu", "kyo", "sha"] },
  { kana: "きゅ", romaji: "kyu", traps: ["kya", "kyo", "shu"] },
  { kana: "きょ", romaji: "kyo", traps: ["kya", "kyu", "sho"] },
  { kana: "しゃ", romaji: "sha", traps: ["shu", "sho", "cha"] },
  { kana: "しゅ", romaji: "shu", traps: ["sha", "sho", "chu"] },
  { kana: "しょ", romaji: "sho", traps: ["sha", "shu", "cho"] },
  { kana: "ちゃ", romaji: "cha", traps: ["chi", "sha", "chu"] },
  { kana: "ちゅ", romaji: "chu", traps: ["cha", "cho", "shu"] },
  { kana: "ちょ", romaji: "cho", traps: ["cha", "sho", "kyo"] },
  { kana: "にゃ", romaji: "nya", traps: ["nyu", "nyo", "hya"] },
  { kana: "にゅ", romaji: "nyu", traps: ["nya", "nyo", "hyu"] },
  { kana: "にょ", romaji: "nyo", traps: ["nya", "nyu", "hyo"] },
  { kana: "ひゃ", romaji: "hya", traps: ["hyu", "hyo", "nya"] },
  { kana: "ひゅ", romaji: "hyu", traps: ["hya", "hyo", "nyu"] },
  { kana: "ひょ", romaji: "hyo", traps: ["hya", "hyu", "nyo"] },
  { kana: "みゃ", romaji: "mya", traps: ["myu", "myo", "nya"] },
  { kana: "みゅ", romaji: "myu", traps: ["mya", "myo", "nyu"] },
  { kana: "みょ", romaji: "myo", traps: ["mya", "myu", "ryo"] },
  { kana: "りゃ", romaji: "rya", traps: ["ryu", "ryo", "mya"] },
  { kana: "りゅ", romaji: "ryu", traps: ["rya", "ryo", "myu"] },
  { kana: "りょ", romaji: "ryo", traps: ["rya", "ryu", "myo"] },
  { kana: "ぎゃ", romaji: "gya", traps: ["gyu", "gyo", "ja"] },
  { kana: "ぎゅ", romaji: "gyu", traps: ["gya", "gyo", "ju"] },
  { kana: "ぎょ", romaji: "gyo", traps: ["gya", "gyu", "jo"] },
  { kana: "じゃ", romaji: "ja", traps: ["ju", "jo", "gya"] },
  { kana: "じゅ", romaji: "ju", traps: ["ja", "jo", "gyu"] },
  { kana: "じょ", romaji: "jo", traps: ["ja", "ju", "gyo"] },
  { kana: "びゃ", romaji: "bya", traps: ["byu", "byo", "pya"] },
  { kana: "びゅ", romaji: "byu", traps: ["bya", "byo", "pyu"] },
  { kana: "びょ", romaji: "byo", traps: ["bya", "byu", "pyo"] },
  { kana: "ぴゃ", romaji: "pya", traps: ["pyu", "pyo", "bya"] },
  { kana: "ぴゅ", romaji: "pyu", traps: ["pya", "pyo", "byu"] },
  { kana: "ぴょ", romaji: "pyo", traps: ["pya", "pyu", "byo"] },
];
