export type KanaItem = {
  kana: string;
  romaji: string;
  traps: string[];
};

export const KATAKANA_DATA: KanaItem[] = [
  { kana: "ア", romaji: "a", traps: ["o", "u", "ya"] },
  { kana: "イ", romaji: "i", traps: ["ri", "e", "chi"] },
  { kana: "ウ", romaji: "u", traps: ["a", "o", "tsu"] },
  { kana: "エ", romaji: "e", traps: ["i", "ke", "sa"] },
  { kana: "オ", romaji: "o", traps: ["a", "u", "ho"] },

  { kana: "カ", romaji: "ka", traps: ["ga", "ko", "ki"] },
  { kana: "キ", romaji: "ki", traps: ["sa", "ka", "gi"] },
  { kana: "ク", romaji: "ku", traps: ["ke", "ta", "gu"] },
  { kana: "ケ", romaji: "ke", traps: ["ku", "se", "ge"] },
  { kana: "コ", romaji: "ko", traps: ["ka", "to", "go"] },

  { kana: "サ", romaji: "sa", traps: ["chi", "ki", "shi"] },
  { kana: "シ", romaji: "shi", traps: ["tsu", "ji", "chi"] },
  { kana: "ス", romaji: "su", traps: ["nu", "mu", "zu"] },
  { kana: "セ", romaji: "se", traps: ["ke", "ze", "e"] },
  { kana: "ソ", romaji: "so", traps: ["n", "zo", "shi"] },

  { kana: "タ", romaji: "ta", traps: ["da", "ku", "chi"] },
  { kana: "チ", romaji: "chi", traps: ["sa", "shi", "tsu"] },
  { kana: "ツ", romaji: "tsu", traps: ["shi", "chi", "su"] },
  { kana: "テ", romaji: "te", traps: ["de", "to", "ke"] },
  { kana: "ト", romaji: "to", traps: ["ko", "do", "te"] },

  { kana: "ナ", romaji: "na", traps: ["ta", "ha", "ma"] },
  { kana: "ニ", romaji: "ni", traps: ["ri", "mi", "i"] },
  { kana: "ヌ", romaji: "nu", traps: ["su", "ne", "mu"] },
  { kana: "ネ", romaji: "ne", traps: ["re", "nu", "me"] },
  { kana: "ノ", romaji: "no", traps: ["ho", "o", "to"] },

  { kana: "ハ", romaji: "ha", traps: ["ba", "pa", "na"] },
  { kana: "ヒ", romaji: "hi", traps: ["bi", "pi", "chi"] },
  { kana: "フ", romaji: "fu", traps: ["hu", "bu", "pu"] },
  { kana: "ヘ", romaji: "he", traps: ["be", "pe", "ho"] },
  { kana: "ホ", romaji: "ho", traps: ["bo", "po", "no"] },

  { kana: "マ", romaji: "ma", traps: ["na", "mu", "me"] },
  { kana: "ミ", romaji: "mi", traps: ["ni", "ri", "bi"] },
  { kana: "ム", romaji: "mu", traps: ["su", "nu", "ma"] },
  { kana: "メ", romaji: "me", traps: ["ne", "re", "ma"] },
  { kana: "モ", romaji: "mo", traps: ["ho", "yo", "to"] },

  { kana: "ヤ", romaji: "ya", traps: ["yu", "a", "ra"] },
  { kana: "ユ", romaji: "yu", traps: ["ya", "yo", "u"] },
  { kana: "ヨ", romaji: "yo", traps: ["yu", "mo", "ro"] },

  { kana: "ラ", romaji: "ra", traps: ["ya", "na", "wa"] },
  { kana: "リ", romaji: "ri", traps: ["i", "ni", "mi"] },
  { kana: "ル", romaji: "ru", traps: ["re", "ro", "u"] },
  { kana: "レ", romaji: "re", traps: ["ne", "ru", "me"] },
  { kana: "ロ", romaji: "ro", traps: ["yo", "ru", "to"] },

  { kana: "ワ", romaji: "wa", traps: ["ra", "ma", "a"] },
  { kana: "ヲ", romaji: "wo", traps: ["o", "wa", "ro"] },
  { kana: "ン", romaji: "n", traps: ["so", "shi", "no"] },

  { kana: "ガ", romaji: "ga", traps: ["ka", "gi", "go"] },
  { kana: "ギ", romaji: "gi", traps: ["ki", "ji", "bi"] },
  { kana: "グ", romaji: "gu", traps: ["ku", "zu", "go"] },
  { kana: "ゲ", romaji: "ge", traps: ["ke", "ze", "go"] },
  { kana: "ゴ", romaji: "go", traps: ["ko", "gu", "ga"] },

  { kana: "ザ", romaji: "za", traps: ["sa", "ji", "zo"] },
  { kana: "ジ", romaji: "ji", traps: ["shi", "gi", "chi"] },
  { kana: "ズ", romaji: "zu", traps: ["su", "gu", "tsu"] },
  { kana: "ゼ", romaji: "ze", traps: ["se", "ge", "de"] },
  { kana: "ゾ", romaji: "zo", traps: ["so", "go", "do"] },

  { kana: "ダ", romaji: "da", traps: ["ta", "de", "ba"] },
  { kana: "ヂ", romaji: "ji", traps: ["chi", "ji", "di"] },
  { kana: "ヅ", romaji: "zu", traps: ["tsu", "zu", "du"] },
  { kana: "デ", romaji: "de", traps: ["te", "ze", "ge"] },
  { kana: "ド", romaji: "do", traps: ["to", "zo", "bo"] },

  { kana: "バ", romaji: "ba", traps: ["ha", "pa", "da"] },
  { kana: "ビ", romaji: "bi", traps: ["hi", "pi", "gi"] },
  { kana: "ブ", romaji: "bu", traps: ["fu", "pu", "gu"] },
  { kana: "ベ", romaji: "be", traps: ["he", "pe", "de"] },
  { kana: "ボ", romaji: "bo", traps: ["ho", "po", "do"] },

  { kana: "パ", romaji: "pa", traps: ["ha", "ba", "ta"] },
  { kana: "ピ", romaji: "pi", traps: ["hi", "bi", "chi"] },
  { kana: "プ", romaji: "pu", traps: ["fu", "bu", "tsu"] },
  { kana: "ペ", romaji: "pe", traps: ["he", "be", "re"] },
  { kana: "ポ", romaji: "po", traps: ["ho", "bo", "to"] },

  { kana: "キャ", romaji: "kya", traps: ["kyu", "kyo", "sha"] },
  { kana: "キュ", romaji: "kyu", traps: ["kya", "kyo", "shu"] },
  { kana: "キョ", romaji: "kyo", traps: ["kya", "kyu", "sho"] },
  { kana: "シャ", romaji: "sha", traps: ["shu", "sho", "cha"] },
  { kana: "シュ", romaji: "shu", traps: ["sha", "sho", "chu"] },
  { kana: "ショ", romaji: "sho", traps: ["sha", "shu", "cho"] },
  { kana: "チャ", romaji: "cha", traps: ["chi", "sha", "chu"] },
  { kana: "チュ", romaji: "chu", traps: ["cha", "cho", "shu"] },
  { kana: "チョ", romaji: "cho", traps: ["cha", "sho", "kyo"] },
  { kana: "ニャ", romaji: "nya", traps: ["nyu", "nyo", "hya"] },
  { kana: "ニュ", romaji: "nyu", traps: ["nya", "nyo", "hyu"] },
  { kana: "ニョ", romaji: "nyo", traps: ["nya", "nyu", "hyo"] },
  { kana: "ヒャ", romaji: "hya", traps: ["hyu", "hyo", "nya"] },
  { kana: "ヒュ", romaji: "hyu", traps: ["hya", "hyo", "nyu"] },
  { kana: "ヒョ", romaji: "hyo", traps: ["hya", "hyu", "nyo"] },
  { kana: "ミャ", romaji: "mya", traps: ["myu", "myo", "nya"] },
  { kana: "ミュ", romaji: "myu", traps: ["mya", "myo", "nyu"] },
  { kana: "ミョ", romaji: "myo", traps: ["mya", "myu", "ryo"] },
  { kana: "リャ", romaji: "rya", traps: ["ryu", "ryo", "mya"] },
  { kana: "リュ", romaji: "ryu", traps: ["rya", "ryo", "myu"] },
  { kana: "リョ", romaji: "ryo", traps: ["rya", "ryu", "myo"] },
  { kana: "ギャ", romaji: "gya", traps: ["gyu", "gyo", "ja"] },
  { kana: "ギュ", romaji: "gyu", traps: ["gya", "gyo", "ju"] },
  { kana: "ギョ", romaji: "gyo", traps: ["gya", "gyu", "jo"] },
  { kana: "ジャ", romaji: "ja", traps: ["ju", "jo", "gya"] },
  { kana: "ジュ", romaji: "ju", traps: ["ja", "jo", "gyu"] },
  { kana: "ジョ", romaji: "jo", traps: ["ja", "ju", "gyo"] },
  { kana: "ビャ", romaji: "bya", traps: ["byu", "byo", "pya"] },
  { kana: "ビュ", romaji: "byu", traps: ["bya", "byo", "pyu"] },
  { kana: "ビョ", romaji: "byo", traps: ["bya", "byu", "pyo"] },
  { kana: "ピャ", romaji: "pya", traps: ["pyu", "pyo", "bya"] },
  { kana: "ピュ", romaji: "pyu", traps: ["pya", "pyo", "byu"] },
  { kana: "ピョ", romaji: "pyo", traps: ["pya", "pyu", "byo"] },
];
